Repository 1oT-organization/hotelity-backend, pull requests merged in 2024-05, with the labels that each got.

#1 [Architectiure] 계층 구조 기본 확립
  src/main/java/org/iot/hotelitybackend/config/CorsConfig.java
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/customer/vo/ResponseCustomer.java
  src/main/java/org/iot/hotelitybackend/dto/BranchDTO.java
  src/main/java/org/iot/hotelitybackend/dto/CampaignDTO.java
  src/main/java/org/iot/hotelitybackend/dto/CustomerDTO.java
  src/main/java/org/iot/hotelitybackend/dto/EmployeeDTO.java
  src/main/java/org/iot/hotelitybackend/dto/MembershipDTO.java
  src/main/java/org/iot/hotelitybackend/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/repository/EmployeeRepository.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/vo/ResponseEmployee.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/BranchEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/BranchController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/BranchRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/ResponseBranch.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/ResponseReservation.java
  src/main/java/org/iot/hotelitybackend/login/controller/LoginController.java
  src/main/java/org/iot/hotelitybackend/login/service/LoginService.java
  src/main/java/org/iot/hotelitybackend/login/service/LoginServiceImpl.java
  src/main/java/org/iot/hotelitybackend/marketing/aggregate/CampaignEntity.java
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignController.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignServiceImpl.java
  src/main/java/org/iot/hotelitybackend/marketing/vo/ResponseCampaign.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipEntity.java
  src/main/java/org/iot/hotelitybackend/sales/controller/MembershipController.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipRepository.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipService.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/ResponseMembership.java
Labels: enhancement

#74 Feat: "전체 고객 리스트 조회"
  src/main/java/org/iot/hotelitybackend/common/config/CorsConfig.java
  src/main/java/org/iot/hotelitybackend/common/constant/Constant.java
  src/main/java/org/iot/hotelitybackend/common/vo/ResponseVO.java
  src/main/java/org/iot/hotelitybackend/config/CorsConfig.java
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/dto/CustomerDTO.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
Labels: enhancement

#76 [Feat] 객실 전체 조회 기능 구현
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/BranchController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/ResponseRoom.java
Labels: enhancement

#79 [Feat] 영업관리 도메인 조회 기능 추가
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/MembershipController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/MembershipIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java
  src/main/java/org/iot/hotelitybackend/sales/dto/CouponDTO.java
  src/main/java/org/iot/hotelitybackend/sales/dto/CouponIssueDTO.java
  src/main/java/org/iot/hotelitybackend/sales/dto/MembershipIssueDTO.java
  src/main/java/org/iot/hotelitybackend/sales/dto/NoticeDTO.java
  src/main/java/org/iot/hotelitybackend/sales/dto/VocDTO.java
  src/main/java/org/iot/hotelitybackend/sales/repository/CouponIssueRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/CouponRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/NoticeRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/VocRepository.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipIssueService.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipIssueServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipService.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocService.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/ResponseVoc.java
Labels: enhancement

#80 [Refactor] 직원 관련 조회 수정
  src/main/java/org/iot/hotelitybackend/employee/aggregate/DepartmentEntity.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/PermissionEntity.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/RankEntity.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/dto/DepartmentDTO.java
  src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java
  src/main/java/org/iot/hotelitybackend/employee/repository/EmployeeRepository.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/vo/ResponseDepartment.java
  src/main/java/org/iot/hotelitybackend/employee/vo/ResponseEmployee.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/BranchEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/ResponseReservation.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipIssueEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java
  src/main/java/org/iot/hotelitybackend/sales/dto/NoticeDTO.java
  src/main/java/org/iot/hotelitybackend/sales/dto/VocDTO.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
Labels: refactor

#81 [Feat] 영업관리/쿠폰등록, 공지등록, 쿠폰발급 기능 추가
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/RequestCoupon.java
  src/main/java/org/iot/hotelitybackend/sales/vo/RequestCouponIssue.java
  src/main/java/org/iot/hotelitybackend/sales/vo/RequestNotice.java
Labels: enhancement

#82 [Feat] 공지사항 수정, 쿠폰 수정, 공지사항 삭제 기능 추가
  src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/RequestModifyNotice.java
Labels: enhancement

#85 [Feat] 지점, 객실 관련 CRUD 기능 구현 완료 (다중 조건 검색 포함)
  build.gradle
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/dto/CustomerDTO.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/BranchEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/BranchController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyBranch.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyRoom.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestRegistBranch.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentTypeController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/PaymentRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentTypeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
Labels: enhancement

#87 [Feat] 호텔서비스 예약, 투숙 조회 및 투숙 등록 기능 구현 완료
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentTypeController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/PaymentDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/PaymentRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/PaymentTypeRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestRegistStay.java
Labels: enhancement

#96 [Refactor] 공지 다중 조건 검색 기능 수정
  src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java
  src/main/java/org/iot/hotelitybackend/sales/dto/NoticeDTO.java
Labels: enhancement

#97 [Feat]마케팅/템플릿,캠페인 조회 기능 추가
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignController.java
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignCustomerController.java
  src/main/java/org/iot/hotelitybackend/marketing/controller/TemplateController.java
  src/main/java/org/iot/hotelitybackend/marketing/dto/CampaignCustomerDTO.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignCustomerRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/TemplateRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignServiceImpl.java
  src/main/java/org/iot/hotelitybackend/marketing/service/TemplateService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/TemplateServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/repository/CouponRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/NoticeRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/VocRepository.java
Labels: enhancement

#98 [Feat] 직원 조회 기능
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmploySpecification.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java
  src/main/java/org/iot/hotelitybackend/employee/repository/EmployeeRepository.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: enhancement

#102 [Refactor] 영업관리/쿠폰, VOC 조건추가(고객코드)
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/VocSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java
  src/main/java/org/iot/hotelitybackend/sales/repository/CouponIssueRepository.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocService.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
Labels: enhancement

#106 [Refactor] 마케팅/캠페인 발송 내역에서 특정 조건 검색 기능 추가
  src/main/java/org/iot/hotelitybackend/marketing/aggregate/CampaignSpecification.java
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignController.java
  src/main/java/org/iot/hotelitybackend/marketing/dto/CampaignDTO.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueSpecification.java
Labels: enhancement

#107 [Feat] 호텔관리 / 객실 CRUD 완료, 부대시설 전체 조회 가능 구현 완료
  build.gradle
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerSpecification.java
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/controller/NationController.java
  src/main/java/org/iot/hotelitybackend/customer/dto/NationDTO.java
  src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/customer/service/NationService.java
  src/main/java/org/iot/hotelitybackend/customer/service/NationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/customer/vo/ResponseNation.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryCategoryEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/AncillaryCategoryDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/AncillaryDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomCategoryRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipIssueEntity.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipRepository.java
Labels: enhancement

#108 [Feat] 호텔서비스/ 투숙 체크아웃 및 결제 조회 기능 구현 완료
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: enhancement

#109 [Feat] 마케팅/템플릿 등록, 수정, 삭제 기능 추가
  src/main/java/org/iot/hotelitybackend/marketing/controller/TemplateController.java
  src/main/java/org/iot/hotelitybackend/marketing/service/TemplateService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/TemplateServiceImpl.java
  src/main/java/org/iot/hotelitybackend/marketing/vo/RequestTemplate.java
Labels: enhancement

#110 [Feat] 호텔관리/부대시설 등록, 수정, 삭제 기능 추가
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyFacility.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestRegistFacility.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/ResponseAncillary.java
Labels: enhancement

#111 [Feat] 호텔서비스/투숙 정보 수정, 삭제 기능 추가
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestModifyStay.java
Labels: enhancement

#113 [Feat] 고객 엑셀 다운로드 기능
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestModifyStay.java
Labels: enhancement

#114 [Feat]특정 고객 정보 조회(고객의 멤버십 포함)
  src/main/java/org/iot/hotelitybackend/customer/dto/CustomerDTO.java
  src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/customer/vo/ResponseCustomer.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
Labels: enhancement

#115 [Feat] 직원 등록/수정/삭제
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/vo/RequestEmployee.java
Labels: enhancement

#119 [Feat] 호텔서비스/투숙 전체 내역 조회, 고객이름별 조회 기능 추가
  build.gradle
  src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomCategoryEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomLevelRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: enhancement

#122 [Feat] 객실, 부대시설 리스트 엑셀 파일 생성 및 다운로드 기능 구현 완료
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
Labels: enhancement

#123 [Feat] 마케팅/캠페인 발송
  build.gradle
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailController.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailService.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailServiceImpl.java
  src/main/java/org/iot/hotelitybackend/smpt/RequestDTO.java
  src/main/java/org/iot/hotelitybackend/smpt/mailDTO.java
  src/test/java/org/iot/hotelitybackend/customer/service/CustomerServiceImplTests.java
Labels: enhancement

#126 [Feat] VOC 엑셀 다운로드
  src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocService.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
Labels: enhancement

#132 [Feat] VOC 삭제
  src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocService.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
Labels: enhancement

#134 [Feat] 멤버십 발급 기능 추가
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/PaymentRepository.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipIssueEntity.java
  src/main/java/org/iot/hotelitybackend/sales/controller/MembershipIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipRepository.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipIssueService.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipIssueServiceImpl.java
Labels: enhancement

#135 [Refactor] 호텔서비스/결제 내역 전체 조회(다중 조건 검색) 코드 리팩토링
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentTypeController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/PaymentDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentTypeService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentTypeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/test/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImplTest.java
Labels: refactor

#140 [Refactor] 엑셀 다운로드 기능 공통 코드로 분리
  src/main/java/org/iot/hotelitybackend/common/util/ExcelUtil.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
Labels: enhancement

#143 [Refactor] 호텔서비스/투숙 내역 전체 조회(다중 조건 검색) 코드 리팩토링
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: refactor

#146 [Feat] 호텔서비스/특정 예약 조회 기능 구현 및 체크인 시 투숙 등록 리팩토링
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestCheckinInfo.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/ResponseStay.java
Labels: enhancement, refactor

#148 [Feat] 호텔서비스/ 투숙 코드로 특정 투숙 내역 조회 기능 구현
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: enhancement, refactor

#153 [Refactor] 호텔서비스/전체 내역 리스트 조회 시 정렬 기능 추가
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerSpecification.java
  src/main/java/org/iot/hotelitybackend/customer/aggregate/NationEntity.java
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/test/java/org/iot/hotelitybackend/customer/service/CustomerServiceImplTests.java
Labels: refactor

#154 [Feat] 마케팅/캠페인 - 캠페인 전체 조회 기능 구현
  src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/aggregate/CampaignCustomerSpecification.java
  src/main/java/org/iot/hotelitybackend/marketing/aggregate/CampaignEntity.java
  src/main/java/org/iot/hotelitybackend/marketing/aggregate/CampaignSpecification.java
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignController.java
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignCustomerController.java
  src/main/java/org/iot/hotelitybackend/marketing/dto/CampaignCustomerDTO.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignCustomerRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignServiceImpl.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailController.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailService.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailServiceImpl.java
  src/main/java/org/iot/hotelitybackend/smpt/RequestDTO.java
  src/main/java/org/iot/hotelitybackend/smpt/mailDTO.java
Labels: enhancement

#160 [Refactor] 영업관리/VOC 및 공지 전체 조회 - 검색 조건 추가/정렬 추가
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/VocSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java
  src/main/java/org/iot/hotelitybackend/sales/dto/NoticeDTO.java
  src/main/java/org/iot/hotelitybackend/sales/dto/VocDTO.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocService.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
Labels: refactor

#162 [Refactor] 쿠폰, 특정고객 정보 조회 기능 수정
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/dto/SelectCustomerDTO.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/dto/CouponIssueDTO.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
Labels: enhancement, refactor

#163 [Refactor] 호텔서비스/투숙 등록 시 객실 수용 인원 반영
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/PaymentDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/PaymentTypeDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestModifyStay.java
Labels: refactor

#166 [Feat] 쿠폰/이메일 - 멤버십 쿠폰 발급 및 메일 전송
  src/main/java/org/iot/hotelitybackend/HotelityBackendApplication.java
  src/main/java/org/iot/hotelitybackend/common/util/ConsoleScheduler.java
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignController.java
  src/main/java/org/iot/hotelitybackend/marketing/repository/CampaignRepository.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
Labels: enhancement

#169 [Refactor] 멤버십 발급 후 쿠폰 발급
  src/main/java/org/iot/hotelitybackend/common/util/ConsoleScheduler.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/controller/MembershipIssueController.java
Labels: refactor

#170 [Feat] 고객/고객등록 한명 고객 등록 기능
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
Labels: enhancement

#172 [Feat] 고객/국가 국가 정보 조회
  src/main/java/org/iot/hotelitybackend/common/config/CorsConfig.java
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/controller/NationController.java
  src/main/java/org/iot/hotelitybackend/customer/dto/NationDTO.java
  src/main/java/org/iot/hotelitybackend/customer/service/NationService.java
  src/main/java/org/iot/hotelitybackend/customer/service/NationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/customer/vo/ResponseNation.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillarySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/AncillaryCategoryRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/AncillaryRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/BranchRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
Labels: enhancement

#173 [Feat] 엑셀/부대시설, 예약, 투숙 리스트 엑셀 다운로드
  src/main/java/org/iot/hotelitybackend/common/util/ExcelUtil.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: enhancement

#175 [Feat] 쿠폰 엑셀 다운로드
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
Labels: enhancement

#177 [Feat] 쿠폰 발급 엑셀 다운로드
  build.gradle
  src/main/java/org/iot/hotelitybackend/HotelityBackendApplication.java
  src/main/java/org/iot/hotelitybackend/common/config/CorsConfig.java
  src/main/java/org/iot/hotelitybackend/common/constant/Constant.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmploySpecification.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeSpecification.java
  src/main/java/org/iot/hotelitybackend/employee/controller/DepartmentController.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/controller/PermissionController.java
  src/main/java/org/iot/hotelitybackend/employee/controller/PositionController.java
  src/main/java/org/iot/hotelitybackend/employee/controller/RankController.java
  src/main/java/org/iot/hotelitybackend/employee/dto/DepartmentDTO.java
  src/main/java/org/iot/hotelitybackend/employee/dto/EmployeeDTO.java
  src/main/java/org/iot/hotelitybackend/employee/dto/PermissionDTO.java
  src/main/java/org/iot/hotelitybackend/employee/dto/PositionDTO.java
  src/main/java/org/iot/hotelitybackend/employee/dto/RankDTO.java
  src/main/java/org/iot/hotelitybackend/employee/repository/EmployeeRepository.java
  src/main/java/org/iot/hotelitybackend/employee/service/DepartmentService.java
  src/main/java/org/iot/hotelitybackend/employee/service/DepartmentServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/service/PermissionService.java
  src/main/java/org/iot/hotelitybackend/employee/service/PermissionServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/service/PositionService.java
  src/main/java/org/iot/hotelitybackend/employee/service/PositionServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/service/RankService.java
  src/main/java/org/iot/hotelitybackend/employee/service/RankServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/vo/ResponseDepartment.java
  src/main/java/org/iot/hotelitybackend/employee/vo/ResponsePermission.java
  src/main/java/org/iot/hotelitybackend/employee/vo/ResponsePosition.java
  src/main/java/org/iot/hotelitybackend/employee/vo/ResponseRank.java
  src/main/java/org/iot/hotelitybackend/login/aggregate/RefreshToken.java
  src/main/java/org/iot/hotelitybackend/login/jwt/JwtFilter.java
  src/main/java/org/iot/hotelitybackend/login/jwt/JwtUtil.java
  src/main/java/org/iot/hotelitybackend/login/repository/RefreshTokenRepository.java
  src/main/java/org/iot/hotelitybackend/login/security/AuthenticationFilter.java
  src/main/java/org/iot/hotelitybackend/login/security/UserLogoutFilter.java
  src/main/java/org/iot/hotelitybackend/login/security/WebSecurityConfig.java
  src/main/java/org/iot/hotelitybackend/login/service/LoginService.java
  src/main/java/org/iot/hotelitybackend/login/service/LoginServiceImpl.java
  src/main/java/org/iot/hotelitybackend/login/vo/LoginUserDetails.java
  src/main/java/org/iot/hotelitybackend/login/vo/RequestLogin.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/repository/CouponIssueRepository.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
Labels: enhancement

#179 [refactor] refactoring excel download
  src/main/java/org/iot/hotelitybackend/common/util/ExcelType.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
Labels: enhancement

#184 [Refactor] 고객 리스트 엑셀 다운로드 코드 수정
  src/main/java/org/iot/hotelitybackend/common/util/ExcelUtil.java
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
Labels: refactor

#186 [Feat] 직원 이미지 업로드
  build.gradle
  src/main/java/org/iot/hotelitybackend/common/config/AwsS3Config.java
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/service/AwsS3Service.java
  src/main/java/org/iot/hotelitybackend/employee/service/AwsS3ServiceImpl.java
Labels: enhancement

#187 [Refactor] 고객 정보 입력 예외처리
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/controller/NationController.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
Labels: refactor

#189 [Refactor] 호텔서비스/예약-ReservationDTO에 StayStatus 추가
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: refactor

#190 [Fix] 고객 조회 시 멤버십등급명, 국가명으로 정렬 가능하게 수정
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerSpecification.java
  src/main/java/org/iot/hotelitybackend/customer/dto/CustomerDTO.java
  src/main/java/org/iot/hotelitybackend/customer/repository/CustomerRepository.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipEntity.java
Labels: bug, refactor

#192 [Feat] 결제 엑셀 다운로드
  src/main/java/org/iot/hotelitybackend/common/util/ExcelType.java
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/PaymentDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
Labels: enhancement

#193 [Refactor] 호텔서비스/투숙-정렬을 위한 Formula 추가
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: enhancement, refactor

#195 [Refactor] 호텔서비스/ReservationDTO와 StayDTO에 숙박일자 추가
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: refactor
