Repository 1oT-organization/hotelity-backend, pull requests merged in 2024-06, with the labels that each got.

#197 [Feat] 객실 각종 미구현 정렬 부분 구현 완료
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomCategoryEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomSpecification.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
Labels: enhancement

#199 [Feat] 연도별 예약 리스트 출력
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
Labels: enhancement

#200 [Refactor] 객실 가격별 정렬 리팩토링
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
Labels: bug, enhancement, refactor

#201 [Feat] 객실 각종 정렬 기능 추가
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
Labels: enhancement

#204 [Refactor] 호텔서비스/예약-예약일자로 예약 내역 조회
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
Labels: refactor

#206 [Feat] 일자별 투숙 리스트 조회
  src/main/java/org/iot/hotelitybackend/common/util/ExcelType.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: enhancement

#208 [Refactor] 호텔서비스/투숙-전체 투숙 내역 조회 성능 개선
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: refactor

#209 [Refactor] 투숙 일자별 리스트 조회 기능
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: bug, refactor

#211 [Feat] 메인페이지용 공지, VOC, 예약 최신순 조회
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/ReservationDashboardVO.java
  src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java
  src/main/java/org/iot/hotelitybackend/sales/repository/NoticeRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/VocRepository.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocService.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/NoticeDashboardVO.java
  src/main/java/org/iot/hotelitybackend/sales/vo/VocDashboardVO.java
Labels: enhancement

#213 [Feat] GPT prompt 완료
  build.gradle
  src/main/java/org/iot/hotelitybackend/chatgpt/controller/CustomBotController.java
  src/main/java/org/iot/hotelitybackend/chatgpt/dto/ChatGPTRequest.java
  src/main/java/org/iot/hotelitybackend/chatgpt/dto/ChatGPTResponse.java
  src/main/java/org/iot/hotelitybackend/chatgpt/dto/Message.java
  src/main/java/org/iot/hotelitybackend/common/config/OpenAIConfig.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#215 [Fix] roomLevelName 안불러와지는 오류 긴급 수정
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
Labels: bug

#216 [Feat] room_image_tb 생성
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomImageEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomImageController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/RoomImageDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/SelectRoomDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomImageRepository.java
Labels: enhancement

#218 [Feat] 객실 조회 시 객실 이미지 리스트 조회
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/RoomImageRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
Labels: enhancement

#219 [Refactor] 지점 조회 코드 수정 및 API 경로 시큐리티 허용 추가
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/BranchController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/BranchServiceImpl.java
  src/main/java/org/iot/hotelitybackend/login/security/WebSecurityConfig.java
Labels: refactor

#220 [Feat] 월별 결제, 예약 데이터로 ChatGPT 프롬프팅
  src/main/java/org/iot/hotelitybackend/chatgpt/controller/ChatGPTController.java
  src/main/java/org/iot/hotelitybackend/chatgpt/controller/CustomBotController.java
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTService.java
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/ReservationEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/PaymentRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java
Labels: enhancement

#221 [Feat] 작년/올해 결제, 예약 데이터로 ChatGPT 프롬프팅
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
Labels: enhancement

#222 [Feat] 템플릿 전체 조회(페이징 없음)
  src/main/java/org/iot/hotelitybackend/marketing/controller/TemplateController.java
  src/main/java/org/iot/hotelitybackend/marketing/service/TemplateService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/TemplateServiceImpl.java
Labels: enhancement

#223 [Feat] 멤버십 등급별 메일 발송
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailController.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailService.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailServiceImpl.java
  src/main/java/org/iot/hotelitybackend/smpt/RequestSendMailByLevelDTO.java
Labels: enhancement

#224 [Refactor] Redis host 경로 수정
  src/main/resources/application.yml
Labels: enhancement, refactor

#225 [Feat] 멤버십 전체 조회 시 페이징 추가
  src/main/java/org/iot/hotelitybackend/sales/controller/MembershipController.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipService.java
  src/main/java/org/iot/hotelitybackend/sales/service/MembershipServiceImpl.java
Labels: enhancement

#226 [Feat] 부대시설 전체 조회 시 정렬 미구현 부분 구현
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
Labels: bug, refactor

#228 [Refactor] 쿠폰 전체조회 시 멤버십등급명으로 정렬 기능 구현
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponEntity.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
Labels: bug, refactor

#230 [Refactor] 영업관리/공지-공지 수정 시 지점 코드 추가
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomCategoryEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/RoomEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/RequestModifyNotice.java
Labels: bug

#231 [Refactor] (일별 or 월별 or 연도별) * (예약 or 결제) 구분하여 GPT 프롬프팅
  src/main/java/org/iot/hotelitybackend/chatgpt/controller/ChatGPTController.java
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTService.java
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
Labels: refactor

#232 [Feat] 현재 시각 기준 어제와 오늘의 공지/VOC 데이터 기반 GPT 프롬프팅
  src/main/java/org/iot/hotelitybackend/chatgpt/controller/ChatGPTController.java
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTService.java
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/repository/NoticeRepository.java
  src/main/java/org/iot/hotelitybackend/sales/repository/VocRepository.java
Labels: enhancement

#233 [Refactor] 호텔서비스/결제-결제 조회 시 고객명, 결제타입명 추가
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
Labels: refactor

#234 [Refactor] 엑셀 업로드시 멤버십 등급 발급
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
  src/main/java/org/iot/hotelitybackend/customer/aggregate/CustomerEntity.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/StayDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: refactor

#235 [Refactor] 호텔서비스/투숙-체크아웃 예정일 정렬 조건 추가
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StaySpecification.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: refactor

#236 [Fix] 더 정확한 결과 도출을 위한 GPT 프롬프팅 명령어 조정
  src/main/java/org/iot/hotelitybackend/chatgpt/controller/ChatGPTController.java
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/ReservationRepository.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java
Labels: bug, refactor

#240 [Refactor] 고객, 직원, 객실 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
  src/main/java/org/iot/hotelitybackend/common/vo/CustomerCriteria.java
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/controller/EmployeeController.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeService.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/vo/EmployeeSearchCriteria.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/RoomController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/RoomServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RoomSearchCriteria.java
Labels: refactor

#242 [Refactor] 부대시설 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/AncillarySearchCriteria.java
Labels: refactor

#244 [Refactor] 결제 로그 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/PaymentController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/PaymentServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/PaymentSearchCriteria.java
Labels: refactor

#246 [Refactor] 로그인 시 Employee 확인 로직 변경, 예약 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/employee/repository/EmployeeRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/ReservationSearchCriteria.java
  src/main/java/org/iot/hotelitybackend/login/service/LoginServiceImpl.java
Labels: refactor

#248 [Refactor] 결제 로그 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/StayController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/StaySearchCriteria.java
Labels: refactor

#250 [Refactor] 캠페인발송 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/marketing/controller/CampaignCustomerController.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerService.java
  src/main/java/org/iot/hotelitybackend/marketing/service/CampaignCustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/marketing/vo/CampaignCustomerSearchCriteria.java
Labels: refactor

#252 [Refactor] 쿠폰, 쿠폰발급 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/CouponIssueSearchCriteria.java
  src/main/java/org/iot/hotelitybackend/sales/vo/CouponSearchCriteria.java
  src/main/resources/application.yml
Labels: refactor

#254 [Hotfix] Reservation 전체 조회 시 Pathvariable 변수명과 criteria 변수명 같아서 생기는 조회 버그 수정
  src/main/java/org/iot/hotelitybackend/hotelservice/controller/ReservationController.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationService.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
Labels: bug

#255 [Fix] Coupon Issue 정렬 안되는 오류 수정
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueEntity.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponIssueController.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
Labels: bug

#257 [Refactor] 공지 전체 조회 시 ModelAttribute 사용하도록 변경
  src/main/java/org/iot/hotelitybackend/sales/aggregate/CouponIssueEntity.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/NoticeEntity.java
  src/main/java/org/iot/hotelitybackend/sales/controller/NoticeController.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponIssueServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeService.java
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/NoticeSearchCriteria.java
Labels: refactor

#259 [Feat] 특정 부대시설 조회 + 이미지 리스트 조회
  src/main/java/org/iot/hotelitybackend/hotelmanagement/aggregate/AncillaryImageEntity.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/controller/AncillaryController.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/AncillaryImageDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/dto/SelectAncillaryDTO.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/repository/AncillaryImageRepository.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryService.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
Labels: enhancement

#261 [Feat] VOC 정렬, 필터 기능 구현 / RequestParam -> ModelAttribute 로 변경
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/VocEntity.java
  src/main/java/org/iot/hotelitybackend/sales/controller/VocController.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocService.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/VocSearchCriteria.java
Labels: enhancement, refactor

#263 [Feat] 파일 다운로드 기능 구현 완료
  src/main/java/org/iot/hotelitybackend/filedownload/controller/FileDownloadController.java
  src/main/resources/tutorial.pdf
Labels: enhancement

#264 [Fix] Employee 정렬, 필터링 안되는 문제 해결
  src/main/java/org/iot/hotelitybackend/employee/aggregate/EmployeeEntity.java
  src/main/java/org/iot/hotelitybackend/employee/service/EmployeeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/employee/vo/EmployeeSearchCriteria.java
Labels: bug

#265 [Refactor] 부대시설 카테고리 이름으로 수정할 수 있게 변경 / 주석 삭제
  src/main/java/org/iot/hotelitybackend/hotelmanagement/service/AncillaryServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyFacility.java
  src/main/java/org/iot/hotelitybackend/sales/controller/CouponController.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponService.java
  src/main/java/org/iot/hotelitybackend/sales/service/CouponServiceImpl.java
Labels: refactor

#267 [Refactor] 호텔서비스/ 투숙 수정 메소드 리팩토링
  src/main/java/org/iot/hotelitybackend/hotelservice/dto/ReservationDTO.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/ReservationServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/RequestModifyStay.java
  src/main/resources/application.yml
Labels: refactor

#268 [Refactor] 투숙 체크아웃예정일, 숙박일수로 정렬 구현
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/StayEntity.java
  src/main/java/org/iot/hotelitybackend/hotelservice/vo/StaySearchCriteria.java
  src/main/java/org/iot/hotelitybackend/sales/service/VocServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/RequestReplyVoc.java
Labels: enhancement, refactor

#271 [Refactor] 캠페인 발송 관련 코드 수정
  src/main/java/org/iot/hotelitybackend/hotelservice/aggregate/PaymentSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/aggregate/MembershipSpecification.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipRepository.java
  src/main/java/org/iot/hotelitybackend/smpt/EmailServiceImpl.java
Labels: refactor

#272 [Refactor] RegistNotice 수정
  src/main/java/org/iot/hotelitybackend/sales/service/NoticeServiceImpl.java
  src/main/java/org/iot/hotelitybackend/sales/vo/RequestNotice.java
Labels: refactor

#273 [Feat] 고객 정보 수정 기능
  src/main/java/org/iot/hotelitybackend/customer/controller/CustomerController.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerService.java
  src/main/java/org/iot/hotelitybackend/customer/service/CustomerServiceImpl.java
  src/main/java/org/iot/hotelitybackend/hotelmanagement/vo/RequestModifyCustomer.java
  src/main/java/org/iot/hotelitybackend/sales/repository/MembershipIssueRepository.java
Labels: enhancement

#274 [Fix] 변수명 제외하고 출력할 수 있게 프롬프팅 수정
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
Labels: bug, refactor

#275 [Fix] 메인페이지 투숙 데이터 조회 오류 수정
  src/main/java/org/iot/hotelitybackend/hotelservice/repository/StayRepository.java
  src/main/java/org/iot/hotelitybackend/hotelservice/service/StayServiceImpl.java
Labels: bug, refactor

#276 [Refactor] tutorial.pdf 파일 업로드
  src/main/java/org/iot/hotelitybackend/filedownload/controller/FileDownloadController.java
Labels: refactor

#277 Refactor: "tutorial.pdf 파일 업로드"
  src/main/java/org/iot/hotelitybackend/filedownload/controller/FileDownloadController.java
Labels: refactor

#278 [Refactor] 프롬프팅 미스매치 수정
  src/main/java/org/iot/hotelitybackend/chatgpt/service/ChatGPTServiceImpl.java
Labels: refactor
